spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/yupi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  session:
    timeout: 86400
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080
mybatis-plus:
  configuration:
    #控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: false # 设置驼峰命名与下划线之间的转换
  # 这里根据自己项目的包修改，扫描到自己的*xml文件
  mapper-locations: classpath:com/czp/usercenter/mapper/*.xml
  # MyBatis Plus相关配置
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)




